name = input("enter your name : ")
age = input("enter your age : ")
home = input("enter your home address : ")
print("student")
print("---------")
print(name + "")
print("my age is" + age)
print("im at " + home)